approach:
  name: NN
  type: CNN_V1
  mode: train
  input_shape:
    - 64
    - 64
    - 3
  optimizer: Adam
  lr: 0.0001
  num_samples: 64722
  num_val_samples: 6798
  batch_size: 32
  epochs: 10
train_gen:
  name: image_generator
  validation_list: C:\Users\oleksandr.vaitovych\PycharmProjects\course_project\data\train\validation_list.txt
  path: C:\Users\oleksandr.vaitovych\PycharmProjects\course_project\data\train\images
val_gen:
  name: validation_images_generator
  validation_list: C:\Users\oleksandr.vaitovych\PycharmProjects\course_project\data\train\validation_list.txt
  path: C:\Users\oleksandr.vaitovych\PycharmProjects\course_project\data\train\images
test_gen:
  name: image_generator
experiments_dir: C:\Users\oleksandr.vaitovych\PycharmProjects\course_project\experiments